apiVersion: v1
kind: Service
metadata:
  name: raoyou
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "raoyou"
    port: 8080
  selector:
    app: raoyou
